In [1]:
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

In [5]:
overture_file_path = Path(".").resolve().parent / "data/interim/overture_data.parquet"

overture_pq = pq.ParquetFile(overture_file_path)
overture_first_100_rows = next(overture_pq.iter_batches(batch_size=100))
overture_df = pa.Table.from_batches([overture_first_100_rows]).to_pandas()

In [6]:
overture_df.head(2)

,id,geometry,longitude,latitude,basic_category,taxonomy_primary,taxonomy_hierarchy,confidence,brand_name
0,b3e0e0b1-8b9b-431e-8c27-9c8181b8d3dd,b'\x01\x01\x00\x00\x00\x9a\xeb4\xd2R\xefS\xc0\...,-79.739430,42.051420,resort,ski_resort,"[lodging, resort, ski_resort]",0.972216,NaN
1,a3b37fef-61d7-4ddf-af5a-06f96800365d,b'\x01\x01\x00\x00\x00W\x840\xf1\xe6\xeeS\xc0\...,-79.732846,42.044927,private_lodging,holiday_rental_home,"[lodging, private_lodging, holiday_rental_home]",0.366379,NaN

In [7]:
lottery_locations_file_path = Path(".").resolve().parent / "data/interim/location_data.parquet"

locations_pq = pq.ParquetFile(lottery_locations_file_path)
locations_first_100_rows = next(locations_pq.iter_batches(batch_size=100))
locations_df = pa.Table.from_batches([locations_first_100_rows]).to_pandas()

In [8]:
locations_df.head(2)

,agtno,busnm,busaddr,buscity,buszip,longitude,latitude
0,97637,TURCA GROCERY CORP,1142 E 165TH ST,BRONX,10459,-73.88748,40.82523
1,102843,VALENCIA BAKERY,499 E 138TH ST,BRONX,10454,-73.91962,40.80773

In [9]:
lottery_sales_file_path = Path(".").resolve().parent / "data/interim/sales_data.parquet"

sales_pq = pq.ParquetFile(lottery_sales_file_path)
sales_first_100_rows = next(sales_pq.iter_batches(batch_size=100))
sales_df = pa.Table.from_batches([sales_first_100_rows]).to_pandas()

In [11]:
sales_df.head(10)

,bus_day,agtno,chain,bustype,numbers_day,numbers_eve,numbers_iw,win4_day,win4_eve,win4_iw,...,money_dots,promo,draw_paid,ig_settles,ig_paid,game0_mm_iw,game1,game2,game3,game4
0,2025-01-01T00:00:00.000,2,0,LOTTERY-VENDOR,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2025-01-01T00:00:00.000,186,0,NYC NEWSSTAND,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2025-01-01T00:00:00.000,448,0,NON PROFIT ORGANIZATION,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2025-01-01T00:00:00.000,529,0,STATIONERY-CARD,250.50,323.50,0.00,426.00,749.00,0.00,...,0.00,0.00,778.00,2250.00,2513.00,0.00,0.00,0.00,0.00,0.00
4,2025-01-01T00:00:00.000,614,0,DRUG STORE,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,250.00,0.00,0.00,0.00,0.00,0.00,0.00
5,2025-01-01T00:00:00.000,708,0,DRUG STORE,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,500.00,0.00,0.00,0.00,0.00,0.00,0.00
6,2025-01-01T00:00:00.000,711,0,NYC NEWSSTAND,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,2025-01-01T00:00:00.000,944,0,NEWS-SMOKE,536.50,568.50,0.00,404.00,476.00,0.00,...,0.00,0.00,609.00,0.00,3681.00,0.00,0.00,0.00,0.00,0.00
8,2025-01-01T00:00:00.000,1027,0,DELI-GROCERY,0.00,20.00,0.00,18.00,42.00,0.00,...,0.00,0.00,54.00,4000.00,622.00,0.00,0.00,0.00,0.00,0.00
9,2025-01-01T00:00:00.000,1090,0,NEWS-SMOKE,725.50,1013.00,5.00,1103.00,1539.50,3.00,...,25.00,0.00,1964.00,4550.00,3365.00,0.00,0.00,0.00,0.00,0.00