In [1]:
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

In [5]:
overture_file_path = Path(".").resolve().parent / "data/interim/overture_data.parquet"

overture_pq = pq.ParquetFile(overture_file_path)
overture_first_100_rows = next(overture_pq.iter_batches(batch_size=100))
overture_df = pa.Table.from_batches([overture_first_100_rows]).to_pandas()

In [6]:
overture_df.head(2)

,id,geometry,longitude,latitude,basic_category,taxonomy_primary,taxonomy_hierarchy,confidence,brand_name
0,b3e0e0b1-8b9b-431e-8c27-9c8181b8d3dd,b'\x01\x01\x00\x00\x00\x9a\xeb4\xd2R\xefS\xc0\...,-79.739430,42.051420,resort,ski_resort,"[lodging, resort, ski_resort]",0.972216,NaN
1,a3b37fef-61d7-4ddf-af5a-06f96800365d,b'\x01\x01\x00\x00\x00W\x840\xf1\xe6\xeeS\xc0\...,-79.732846,42.044927,private_lodging,holiday_rental_home,"[lodging, private_lodging, holiday_rental_home]",0.366379,NaN

In [7]:
lottery_locations_file_path = Path(".").resolve().parent / "data/interim/location_data.parquet"

locations_pq = pq.ParquetFile(lottery_locations_file_path)
locations_first_100_rows = next(locations_pq.iter_batches(batch_size=100))
locations_df = pa.Table.from_batches([locations_first_100_rows]).to_pandas()

In [8]:
locations_df.head(2)

,agtno,busnm,busaddr,buscity,buszip,longitude,latitude
0,97637,TURCA GROCERY CORP,1142 E 165TH ST,BRONX,10459,-73.88748,40.82523
1,102843,VALENCIA BAKERY,499 E 138TH ST,BRONX,10454,-73.91962,40.80773