# CANDIDATE FEATURE IDENTIFICATION
The purpose of this notebook is to aggregate in one location the potential features to include in the training set. 
Inputs: External Dataset Parquet Files. 
Desired Outputs: 
- Of redundant variables, select the most reliable and informative one. 
- Understand how to calculate any computed features.

Notes
- Use a separate .py module under src/external_dataset_name/ingest.py to pull in the data with API or other method and write to data/interim/external_dataset_name.parquet. 
- This notebook should read in just a small sample of each dataset for feature exploration. Reading in the full dataset may crash the Jupyter kernel. 

For each feature, attempt to identify:
- time of observation
- unit of observation / what it actually is
- geographic scope (i.e. is it at the census block group, tract, or zip code level?)
- missingness
- what preprocessing is required (e.g. geocoding to census block group, converting a raw count to density)

In [ ]:
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

In [2]:
pd.set_option('display.max_columns', None)

## Lottery and Sales Data (for reference when merging)

In [13]:
lottery_locations_file_path = Path(".").resolve().parent / "data/interim/location_data.parquet"

#locations_pq = pq.ParquetFile(lottery_locations_file_path)
#locations_first_100_rows = next(locations_pq.iter_batches(batch_size=100))
#locations_df = pa.Table.from_batches([locations_first_100_rows]).to_pandas()

locations_df = pd.read_parquet(str(lottery_locations_file_path))

In [14]:
locations_df.head(2)

,agtno,busnm,busaddr,buscity,buszip,longitude,latitude
0,97637,TURCA GROCERY CORP,1142 E 165TH ST,BRONX,10459,-73.88748,40.82523
1,102843,VALENCIA BAKERY,499 E 138TH ST,BRONX,10454,-73.91962,40.80773

In [15]:
lottery_sales_file_path = Path(".").resolve().parent / "data/final/sales_data.parquet"

#sales_pq = pq.ParquetFile(lottery_sales_file_path)
#sales_first_100_rows = next(sales_pq.iter_batches(batch_size=1000))
#sales_df = pa.Table.from_batches([sales_first_100_rows]).to_pandas()

sales_df = pd.read_parquet(str(lottery_sales_file_path))

In [16]:
sales_df.sample(5)

,agtno,total_sales,first_date,last_date,first_pos_date,last_pos_date,pos_sales_days,num_cal_days,num_active_days,days_before_first_sale,days_after_last_sale,avg_cal_daily_sales,avg_active_daily_sales,use_active_period,avg_daily_sales
4395,112209,484393.5,2025-01-01,2025-12-31,2025-01-01,2025-12-31,359.0,365,365.0,0.0,0.0,1327.105479,1327.105479,False,1327.105479
151,100757,713872.5,2025-01-01,2025-12-31,2025-01-01,2025-12-31,365.0,365,365.0,0.0,0.0,1955.815068,1955.815068,False,1955.815068
1048,103859,1031533.5,2025-01-01,2025-12-31,2025-01-02,2025-12-31,364.0,365,364.0,1.0,0.0,2826.119178,2833.883242,False,2826.119178
12419,78304,492015.5,2025-01-01,2025-12-31,2025-01-01,2025-12-31,365.0,365,365.0,0.0,0.0,1347.987671,1347.987671,False,1347.987671
7120,115853,266099.0,2025-06-14,2025-12-31,2025-06-14,2025-12-31,201.0,201,201.0,0.0,0.0,1323.875622,1323.875622,False,1323.875622

## Overture Maps Data

In [6]:
overture_file_path = Path(".").resolve().parent / "data/interim/overture_data.parquet"

overture_pq = pq.ParquetFile(overture_file_path)
overture_first_100_rows = next(overture_pq.iter_batches(batch_size=100))
overture_df = pa.Table.from_batches([overture_first_100_rows]).to_pandas()

In [7]:
overture_df.head(2)

,id,geometry,longitude,latitude,basic_category,taxonomy_primary,taxonomy_hierarchy,confidence,brand_name
0,b3e0e0b1-8b9b-431e-8c27-9c8181b8d3dd,b'\x01\x01\x00\x00\x00\x9a\xeb4\xd2R\xefS\xc0\...,-79.739430,42.051420,resort,ski_resort,"[lodging, resort, ski_resort]",0.972216,NaN
1,a3b37fef-61d7-4ddf-af5a-06f96800365d,b'\x01\x01\x00\x00\x00W\x840\xf1\xe6\xeeS\xc0\...,-79.732846,42.044927,private_lodging,holiday_rental_home,"[lodging, private_lodging, holiday_rental_home]",0.366379,NaN